### ISSUE TITLE
Incorrect brightness value retrieved for gosund dimmer switch

### ISSUE THREAD

**Issue by Dilbert66** [nuttytree/ESPHome-Devices#1]
Just a quick note, I've been trying out your yaml for the Tuya and Gosund dimmers and quite liking them but found an issue with the value that is retrieved form the LightState class specifically the current_values_as_brightness.   This value gets gamma corrected before being returned (a power factor of 2.8 by default I believe) which does not give the correct percentage value expected by serial output.   Setting the gamma_correct value as 1 in the light section of your yaml ie lights will correct this value.  Alternatively you could use a different class call to get the correct value but this was the easiest way to accomplish this at this time.   This is noticeble if you turn off the switch manually at one level, it will turn back on at a lower level because of the descrepency. 

  - id: gosund_light
    name: ${device_name}
    default_transition_length: 0s
    gamma_correct: 1.0

**Comment by nuttytree** [comment]
I had actually abandoned the Gosund dimmers, both lights I tried them on had major flickering/buzzing issues.  Now I wonder if this was part of the issue.  I will take a closer look at this to see where it makes the most sense to fix it.

**Comment by Dilbert66** [comment]
I've been quite pleased with them so far. Also use the Feit dimmers with your code and those work fine as well.   Another note, I borrowed code from another implementation that prevents the inputs from the user from being resent to the coprocessor since it's repetitive as the light has already been manually set at the switch.  Here's the link to the other version.
https://community.home-assistant.io/t/esphome-custom-component-any-way-to-publish-a-light-state-manually/159757

**Comment by nuttytree** [comment]
@Dilbert66 I think this commit should correct the issue [ebb35f4](https://github.com/nuttytree/ESPHome-Devices/commit/ebb35f4a0ef7d2cefa0baeddac437a6659a593bb).
