### ISSUE TITLE
Help needed setting up light with power

### ISSUE THREAD

**Issue by jaroslavas** [nuttytree/ESPHome-Devices#46]
I've added light with power component as described in readme:

```
external_components:
  - source: github://nuttytree/esphome
    components: [ binary_light_with_power ]
```

But it doesn't wan't to work, giving me an error:

Result: 
```INFO Reading configuration /config/switch.yaml...
Failed config

external_components: [source /config/switch.yaml:13]
  - source: github://nuttytree/esphome
    components: 
      
      Could not find __init__.py file for component binary_light_with_power. Please check the component is defined by this source (search path: /config/.esphome/external_components/63b570de/esphome/components/binary_light_with_power/__init__.py).
      - binary_light_with_power
   ```

Any ideas what I am doing wrong? :)

**Comment by nuttytree** [comment]
To be honest my life has been a crazy mess the last year and I have not kept up on updates to this repo.  I feel like I had to make a change a while back to support a newer version of ESPHome but I could be wrong.  I don't have time to take look now but I should be able to some time this week.

**Comment by nuttytree** [comment]
Sorry this took so long to get back to you on this.  I found the issue, it was a typo in the README's.  The correct path for the source is `github://nuttytree/ESPHome-Devices`.  I have updated all of the README's in this PR #47.
